In [18]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
import numpy as np
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

In [10]:
df=pd.read_csv("datasets/car-sales-extended.csv")

Make sure the data is numerical

In [11]:
df.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [12]:
df.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [15]:
x=df.drop('Price',axis=1)
y=df['Price']

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7)

In [17]:
model=RandomForestRegressor()
model.fit(x_train,y_train)

ValueError: could not convert string to float: 'Nissan'

need to covert to number as model cam't handle string

In [58]:
categorical_features=["Make","Colour","Doors"]
one_hot=OneHotEncoder(handle_unknown='ignore')
transformer=ColumnTransformer([("one_hot",one_hot,categorical_features)],remainder="passthrough")


In [20]:
x_transformed=transformer.fit_transform(x)

In [23]:
pd.DataFrame(x_transformed)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [26]:
pd.get_dummies(x[["Make","Colour","Doors"]],dtype='int64')

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4         0           1            0            0             0   
1        5         1           0            0            0             0   
2        4         0           1            0            0             0   
3        4         0           0            0            1             0   
4        3         0           0            1            0             0   
..     ...       ...         ...          ...          ...           ...   
995      4         0           0            0            1             1   
996      3         0           0            1            0             0   
997      4         0           0            1            0             0   
998      4         0           1            0            0             0   
999      4         0           0            0            1             0   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0              0             0           0             1  
1              1             0           0             0  
2              0             0           0             1  
3              0             0           0             1  
4              1             0           0             0  
..           ...           ...         ...           ...  
995            0             0           0             0  
996            0             0           0             1  
997            1             0           0             0  
998            0             0           0             1  
999            1             0           0             0  

[1000 rows x 10 columns]

In [27]:
np.random.seed(42)

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x_transformed,y,train_size=0.7)

In [47]:
model=RandomForestRegressor(n_estimators=350)
model.fit(x_train,y_train)

RandomForestRegressor(n_estimators=350)

In [48]:
model.score(x_test,y_test)

0.28813207811683206

Handling missing values

In [50]:
missing_df=pd.read_csv("datasets/car-sales-extended-missing-data.csv")

In [52]:
missing_df

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [51]:
missing_df.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [53]:
x=df.drop('Price',axis=1)
y=df['Price']

In [59]:
x_transformed=transformer.fit_transform(x)

In [64]:
pd.DataFrame(x_transformed).shape

(1000, 13)

In [63]:
x.shape

(1000, 4)

In [65]:
missing_df["Make"].fillna("missing",inplace=True)
missing_df["Colour"].fillna("missing",inplace=True)
missing_df["Odometer (KM)"].fillna(missing_df['Odometer (KM)'].mean(),inplace=True)
missing_df["Doors"].fillna(4,inplace=True)

C:\Users\dilip\AppData\Local\Temp\ipykernel_8364\315560326.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  missing_df["Colour"].fillna("missing",inplace=True)
C:\Users\dilip\AppData\Local\Temp\ipykernel_8364\315560326.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For exam

In [66]:
missing_df.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [71]:
#removing price rows which are missing
missing_df.dropna(subset=['Price'],inplace=True)

In [72]:
missing_df.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [122]:
x=missing_df.drop('Price',axis=1)
y=missing_df['Price']

In [123]:
x_train,x_test,y_train,y_test=train_test_split(x_transformed,y,train_size=0.7)

In [124]:
x_transformed=transformer.fit_transform(x)

transforming with sklearn

In [129]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [143]:
missing_df=pd.read_csv("datasets/car-sales-extended-missing-data.csv")
missing_df.dropna(subset=["Price"],inplace=True)
x=missing_df.drop('Price',axis=1)
y=missing_df['Price']

In [144]:
x.isnull().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
dtype: int64

In [ ]:
cat_imputer=SimpleImputer(strategy="constant",fill_value="missing")
door_imputer=SimpleImputer(strategy="constant",fill_value=4)
num_imputer=SimpleImputer(strategy="mean")
imputer =ColumnTransformer([("cat",cat_imputer,["Make","Colour"]),("num",num_imputer,["Odometer (KM)"]),("door",door_imputer,["Doors"])],remainder="passthrough")

In [146]:
imputed_x=imputer.fit(x)

In [147]:
imputed_x

ColumnTransformer(remainder='passthrough',
                  transformers=[('cat',
                                 SimpleImputer(fill_value='missing',
                                               strategy='constant'),
                                 ['Make', 'Colour']),
                                ('num', SimpleImputer(), ['Odometer (KM)']),
                                ('door',
                                 SimpleImputer(fill_value=4,
                                               strategy='constant'),
                                 ['Doors'])])

In [148]:
imputed_x=imputer.fit_transform(x)

In [178]:
x=pd.DataFrame(imputed_x,columns=x.columns.get_level_values(0))

In [179]:
x

Make Colour Odometer (KM) Doors
0      Honda  White       35431.0   4.0
1        BMW   Blue      192714.0   5.0
2      Honda  White       84714.0   4.0
3     Toyota  White      154365.0   4.0
4     Nissan   Blue      181577.0   3.0
..       ...    ...           ...   ...
945   Toyota  Black       35820.0   4.0
946  missing  White      155144.0   3.0
947   Nissan   Blue       66604.0   4.0
948    Honda  White      215883.0   4.0
949   Toyota   Blue      248360.0   4.0

[950 rows x 4 columns]

In [180]:
x.isnull().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
dtype: int64

In [190]:
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("onehot",one_hot,["Make","Colour","Doors"])],remainder="passthrough")

In [191]:
x.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors'], dtype='object')

In [192]:
tranformed_x=transformer.fit_transform(x)

In [198]:
tranformed_x

<950x15 sparse matrix of type '<class 'numpy.float64'>'
	with 3800 stored elements in Compressed Sparse Row format>

In [205]:
x_train,x_test,y_train,y_test=train_test_split(tranformed_x,y,test_size=0.2)

In [212]:
model=RandomForestRegressor(n_estimators=10000)
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.3347180854155587

In [222]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_curve

In [216]:
print(cross_val_score(model,tranformed_x,y))

[0.10127057 0.25884569 0.29040997 0.19643512 0.27874517]


ROC receiver operating Characteristic

In [217]:
heart_df=pd.read_csv("datasets/heart-disease.csv")

In [219]:
x,y=heart_df.drop("target",axis=1),heart_df["target"]

In [221]:
cross_val_score(RandomForestClassifier(),x,y)

array([0.80327869, 0.90163934, 0.80327869, 0.81666667, 0.76666667])

In [223]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.75)

In [225]:
RFC_model=RandomForestClassifier()

In [226]:
RFC_model.fit(x_train,y_train)

RandomForestClassifier()

In [228]:
y_prob=RFC_model.predict_proba(x_test)
y_prob_positive=y_prob[:,1]

In [230]:
fpr,tpr,threshold=roc_curve(y_test,y_prob_positive)

In [231]:
fpr

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.03333333, 0.06666667, 0.06666667,
       0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
       0.1       , 0.1       , 0.13333333, 0.13333333, 0.16666667,
       0.16666667, 0.26666667, 0.5       , 0.53333333, 0.86666667,
       0.93333333, 1.        ])

In [ ]:
def plot_roc_curve(fpr,tpr):
    plt.plot(fbr,tpr,color="orange",label="ROC")